### ISSUE TITLE
EOL `commonLibCLPaths`

### ISSUE THREAD

**Issue by basil** [jenkinsci/winstone#208]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Winstone 5.22
Jenkins 2.334
Ubuntu 20.04.3 LTS x86_64

### Reproduction steps

Run `git grep -i commonLibCLPaths`.

### Expected Results

The search returns zero results.

### Actual Results

The search returns a nonzero number of results.

### Anything else?

I could find no references to `commonLibCLPaths` [anywhere in the Jenkins ecosystem](https://github.com/search?type=Code&q=user%3Ajenkinsci+commonLibCLPaths%60). In this repository, we populate `commonLibCLPaths` without ever consuming it, so it is dead code. There are no usages `HostConfiguration` or `HostGroup` outside of this repository, either. This dead code seems best left in the rear-view mirror. My suggestion is to remove all references to `commonLibCLPaths` from this repository.

**Comment by olamy** [comment]
definitely something to do. but being a bit cautious when touching public api (see my comments from https://github.com/jenkinsci/winstone/pull/206#issuecomment-1033066863)
