### ISSUE TITLE
Winstone uses deprecated `git://` protocol

### ISSUE THREAD

**Issue by basil** [jenkinsci/winstone#215]
### Jenkins and plugins versions report

Jenkins: 2.339
OS: Ubuntu 20.04.4 LTS x86_64

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

Run `git grep 'git:\/\/'` in this repository.

### Expected Results

No usages of the deprecated `git://` protocol should be found.

### Actual Results

A usage of the deprecated `git://` protocol is found:

```xml
$ git grep 'git:\/\/'
pom.xml:    <connection>scm:git:git://github.com/${gitHubRepo}.git</connection>
```

### Anything else?

From [Improving Git protocol security on GitHub](https://github.blog/2021-09-01-improving-git-protocol-security-github/):

> If any [URLs] start with `git://`, you should [change the URL](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#changing-a-remote-repositorys-url) to a supported format.

I suggest changing the URL to the non-deprecated version:

```xml
<connection>scm:git:https://github.com/${gitHubRepo}.git</connection>
```

**Comment by olamy** [comment]
sounds good.
just make a PR

**Comment by basil** [comment]
> sounds good.

Thanks!

> just make a PR

If and when I am interested in opening a pull request, I will do so. Thanks!

**Comment by olamy** [comment]
fixed in https://github.com/jenkinsci/winstone/commit/81fc09f018433d7c2d0f95dad47043198ed71248
