### ISSUE TITLE
Launcher should atomically write port to file 

### ISSUE THREAD

**Issue by Pldi23** [jenkinsci/winstone#248]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
 jenkins-test-harness-1816.v8138d8056949
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

MacOs

### Reproduction steps

To reproduce you could run hundreds of time [RemoteArtifactCopyBuilderTest](https://github.com/cloudbees/operations-center-context/blob/master/src/test/java/com/cloudbees/opscenter/artifacts/RemoteArtifactCopyBuilderTest.java#L98) and see them flaky. But keep in mind that you should use jenkins-test-harness <= [1816.v8138d8056949](https://github.com/jenkinsci/jenkins-test-harness/releases/tag/1816.v8138d8056949), as jenkins-test-harness going to patch  [workaround](https://github.com/jenkinsci/jenkins-test-harness/pull/465).

### Expected Results

Tests should not flake

### Actual Results

tests are flaky

### Anything else?

https://github.com/jenkinsci/winstone/blob/4754da67bf797b906a5c858b2de63b97ac609543/src/main/java/winstone/Launcher.java#L221-L242
should write port value atomically.

For a context related conversation https://github.com/jenkinsci/jenkins-test-harness/pull/465#discussion_r936638840

**Comment by jglick** [comment]
https://github.com/jenkinsci/jenkins/blob/6ceadb3e39895cda13adb7efab371018b739b7cb/core/src/main/java/hudson/util/AtomicFileWriter.java#L195 for example
