### ISSUE TITLE
Expose setExcludeProtocols as a CLI option

### ISSUE THREAD

**Issue by 4x0v7** [jenkinsci/winstone#308]
### What feature do you want to see added?

The list of disabled SSL(TLS) protocol versions is currently [hard-coded as](https://github.com/jenkinsci/winstone/blob/4010fa1abd2dd8a881b7abd7934fc8d7e7efaf47/src/main/java/winstone/AbstractSecuredConnectorFactory.java#L103)
"SSLv3", "SSLv2", "SSLv2Hello"

It would be nice to have this as a configurable option, for example to disable TLSv1.2 to have only TLS 1.3 enabled

**Comment by basil** [comment]
Seems reasonable; are you interested in opening a pull request?

**Comment by 4x0v7** [comment]
Sure, have opened a PR
