### ISSUE TITLE
Support for JEP380 Unix Domain Sockets as provided by Jetty

### ISSUE THREAD

**Issue by minfrin** [jenkinsci/winstone#345]
### What feature do you want to see added?

Jetty supports JEP380 Unix Domain Sockets.

Add the required command line options and constructors to use Unix Domain Sockets as per Jetty docs.

### Upstream changes

https://webtide.com/unixdomain-support-in-jetty/
https://eclipse.dev/jetty/documentation/jetty-11/programming-guide/index.html#pg-server-http-connector

**Comment by MarkEWaite** [comment]
Can you further explain how Unix domain socket support in Winstone would help Jenkins users?  The benefit is not clear to me.

**Comment by MarkEWaite** [comment]
> Socket files on a filesystem can have filesystem permissions as well as SELinux permissions applied to them, thus providing a mechanism to force incoming requests to pass through a web application firewall running in front of Jenkins.

Doesn't a reverse proxy configuration already provide most of the benefits of that type of isolation?  The Jenkins controller can be configured to listen only on the localhost interface and then allow the nginx or Apache reverse proxy to handle the traffic outside the machine.

**Comment by daniel-beck** [comment]
(Obligatory disclaimer: Not a maintainer of this repo, or packaging)

Please consider submitting a PR for https://www.jenkins.io/doc/book/installing/initial-settings/ (and possibly related pages on jenkins.io) to document this beyond the Winstone CLI help.

**Comment by MarkEWaite** [comment]
> Please consider submitting a PR for https://www.jenkins.io/doc/book/installing/initial-settings/ (and possibly related pages on jenkins.io) to document this beyond the Winstone CLI help.

I think that it would also be much appreciated if the reverse proxy configuration instructions were extended to include Unix domain sockets support.  I assume that the most popular reverse proxies are the first choice, like:

* [Apache](https://www.jenkins.io/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-apache/)
* [Nginx](https://www.jenkins.io/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx/)

I assume it would not apply to the following reverse proxies:

* [Internet Information Server (IIS)](https://www.jenkins.io/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iis/) - Windows specific
* [IPtables](https://www.jenkins.io/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iptables/) - handling requests in the Linux kernel, Unix domain socket not likely supported in that context
